[package]

# Semantic Versioning is used: https://semver.org/
version = "2.3.0"

# Description
category = "isaaclab"
readme = "README.md"

title = "RL Extension Library for Robots, Based on IsaacLab."
author = "Carsten Oertel"
maintainer = "Carsten Oertel"
description = "RL Extension Library for Robots, Based on IsaacLab."
repository = ""
keywords = ["extension", "fr3_tekken_adof", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "fr3_tekken_adof"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
